# The overall template of the release notes
template: |
  Compatible with OpenSearch 2.13.0
  $CHANGES

# Setting the formatting and sorting for the release notes body
name-template: Version 1.0.0
change-template: '* $TITLE ([#$NUMBER]($URL))'
sort-by: merged_at
sort-direction: ascending
replacers:
  - search: '##'
    replace: '###'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking change'
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Infrastructure'
    labels:
      - 'build'
      - 'testing'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'version compatibility'
      - 'maintenance'
  - title: 'Refactoring'
    labels:
      - 'refactor'