version: '3.7'

services:

  dataprepper-dev-os:
    depends_on:
      - ubi-dev-os
      - ubi-dev-os-2
      - ubi-dev-os-3
    container_name: dataprepper
    image: opensearchproject/data-prepper:2.8.0
    ports:
      - 4900:4900
      - 2021:2021
    volumes:
      - ./dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./dataprepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml 
    networks:
      - ubi-dev-os-net

  ubi-dev-os:
    build: ./
    environment:
      node.name: os01
      discovery.seed_hosts: os01,os02,os03
      cluster.initial_master_nodes: os01,os02,os03
      plugins.security.disabled: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      cluster.name: os-cluster
      network.host: 0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - ubi-dev-os-net

  ubi-dev-os-2:
    build: ./
    environment:
      node.name: os02
      discovery.seed_hosts: os01,os02,os03
      cluster.initial_master_nodes: os01,os02,os03
      plugins.security.disabled: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      cluster.name: os-cluster
      network.host: 0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - ubi-dev-os-net

  ubi-dev-os-3:
    build: ./
    environment:
      node.name: os03
      discovery.seed_hosts: os01,os02,os03
      cluster.initial_master_nodes: os01,os02,os03
      plugins.security.disabled: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      cluster.name: os-cluster
      network.host: 0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - ubi-dev-os-net

  os-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      OPENSEARCH_HOSTS: '["http://os01:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - os01
    networks:
      - ubi-dev-os-net