version: '3'

services:
  opensearch:
    build: ./
    # TODO: maybe rename the demo opensearch node instead
    container_name: opensearch_ubi  #Chorus demo already has an `opensearch` container
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
#      See https://forum.opensearch.org/t/how-to-enable-cors-cross-origin-resource-sharing/426/3 for more
      http.cors.enabled: true 
#      Warning: this is opening it up to all cross domains
#      http.cors.allow-origin: "http://localhost"...
      http.cors.allow-origin: "*"
      http.cors.allow-methods: OPTIONS,TRACE,HEAD,GET,POST,PUT,DELETE
      http.cors.allow-credentials: true
      # TODO: add REST headers required here
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      plugins.ubi.indices: "awesome"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - 9200
      - 9600
    networks:
      - opensearch-net

  # opensearch-dashboards:
  #   build: ./dashboard-plugin/
  #   container_name: opensearch-dashboards
  #   ports:
  #     - 5601:5601
  #   expose:
  #     - 5601
  #   environment:
  #     OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
  #   networks:
  #     - opensearch-net
  #   depends_on:
  #     - opensearch

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge
