name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Dtests.security.manager=false clean test
    # - name: Publish packages to GitHub packages
    #   run: ./gradlew publishPluginZipPublicationToSnapshotsRepository
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
