name: Build and Test
on:
  push:
    branches:
      - 2.12.0
      - 2.13.0
      - 2.14.0
  pull_request:
  workflow_dispatch:
env:
  PLUGIN_NAME: opensearch-ubi
jobs:
  plugin-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [11, 17, 21]
        experimental: [false]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - id: random-password
        uses: peternied/random-name@v1
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Assemble target plugin
        uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true
          arguments: assemble
      - name: Move and rename the plugin for installation
        run: mv ./build/distributions/${{ env.PLUGIN_NAME }}-*.zip ${{ env.PLUGIN_NAME }}.zip
        shell: bash
      - name: Run Opensearch with a single plugin
        uses: derek-ho/start-opensearch@v3
        with:
          opensearch-version: ${GITHUB_REF##*/}
          plugins: "file:$(pwd)/${{ env.PLUGIN_NAME }}.zip"
          security-enabled: false
          admin-password: ${{ steps.random-password.outputs.generated_name }}
